apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-2es6kp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-2es6kp
  namespace: my-nginx-2es6kp
  labels:
    name: nginx-2es6kp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-2es6kp
  template:
    metadata:
      namespace: my-nginx-2es6kp
      labels:
        name: nginx-2es6kp
    spec:
      containers:
      - name: nginx-2es6kp
        image: nginx
        ports:
        - containerPort: 80

